# 스프링 부트 2.4 이전에는 default 영역으로 인식되었지만,
# 스프링 부트 2.4 부터는 제일 마지막 정의된 내용으로 덮어씌워진다.

daemon:
  nick-name: Developer local
  root-uri: "https://127.0.0.1:8443"

---

spring:
  profiles: daemon-local

daemon:
  nick-name: Developer local
  root-uri: "http://127.0.0.1:8080"

---
spring:
  profiles: daemon-dev

daemon:
  nick-name: Developer dev
  root-uri: "https://127.0.0.1:8443"

---
spring:
  profiles: daemon-live

daemon:
  nick-name: Developer live
  root-uri: "http://127.0.0.1:9090"


